// @ts-check
/**
 * esbuild build script for AI Agent Orchestrator VS Code Extension
 *
 * Outputs:
 *   dist/extension.js  — Extension host (CommonJS, Node, external:vscode)
 *   dist/webview.js    — Webview React bundle (ESM)
 *   dist/webview.css   — Extracted CSS (auto-generated by esbuild from CSS imports)
 */

const esbuild = require('esbuild');
const path = require('path');

const watch = process.argv.includes('--watch');
const minify = !watch;

/** @type {import('esbuild').BuildOptions} */
const extensionOptions = {
  entryPoints: ['src/extension.ts'],
  bundle: true,
  outfile: 'dist/extension.js',
  external: ['vscode'],
  format: 'cjs',
  platform: 'node',
  sourcemap: watch ? 'inline' : false,
  minify,
  logLevel: 'info',
};

/** @type {import('esbuild').BuildOptions} */
const webviewOptions = {
  entryPoints: ['src/webview/index.tsx'],
  bundle: true,
  outfile: 'dist/webview.js',
  format: 'esm',
  jsx: 'automatic',
  sourcemap: watch ? 'inline' : false,
  minify,
  loader: {
    '.css': 'css',
  },
  logLevel: 'info',
};

async function build() {
  if (watch) {
    const [extCtx, webCtx] = await Promise.all([
      esbuild.context(extensionOptions),
      esbuild.context(webviewOptions),
    ]);

    await Promise.all([extCtx.watch(), webCtx.watch()]);
    console.log('[esbuild] Watching for changes…');
  } else {
    await Promise.all([
      esbuild.build(extensionOptions),
      esbuild.build(webviewOptions),
    ]);
    console.log('[esbuild] Build complete.');
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
